### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by nagdawi** [iwyoo/DIRNet-tensorflow#4]
I have 3 questions:
1. why do you choose 10,000 iterations? I think this is big number for small images and it takes about 2 days to execute without GPU.
2. How can we calculate the algorithm accuracy?
3. How can we modify the code to find transformation parameters between fixed and floating images in case of image registration?

Thanks for sharing your code

**Comment by iwyoo** [comment]
1. Actually it is not a big number of iterations with GPU. You can change the number if you want. 
2. You can check the metric used in the original paper. For MNIST, you can just use NCC or SSIM. Because the images are very simple.
3. You can check the earlier closed issue.  https://github.com/iwyoo/DIRNet-tensorflow/issues/3
