### ISSUE TITLE
How to evaluate the algorithm by the average 2D Euclidean distance between a landmark in the warped image and its corresponding landmark in the fixed image?

### ISSUE THREAD

**Issue by h1310321230** [iwyoo/DIRNet-tensorflow#5]
If I feed the the pair of the test images(fixed image and moved image) into the model trained well. I can easily get the registed image. But, If I select several point in the moved image, their coordinates like that (x1, y1), (x2, y2) ... (x10, y10). Thoes points put into the model trained well and do this deformable transformation. After that, I want to know how I can get thoes changed coordinates. I want to evaluate the algorithm by calculating the average 2D Euclidean distance between a landmark in the warped image and its corresponding landmark in the fixed image . Thanks in advance.

**Comment by iwyoo** [comment]
https://github.com/iwyoo/DIRNet-tensorflow/blob/master/WarpST.py#L127
You can check this tensor. This tensor has the (relative) referencing position of the image. I say 'referencing' because warping is based on sampling by warping vectors. When you just move the pixels separately, there must be holes. To prevent it, usually, warped images are sampled from moving images for each pixel in the warped images.
The relative space is (as following the STN original paper) from -1 to 1. It means the T_g tensor is normalized. You should check '_meshgrid' to understand this.
However, I just recommend you to do differently. First, find the vector flow that you want to compare. And, prepare an image with landmarks. Warp the landmark image by the vector flow. Now, you get a warped landmark image. This landmark image is (smoothly) interpolated, so you need to get exact positions by other approach like non-maximum suppression. Then, you can calculated the euclidean distance. Good luck!
